[project]
name = "griptape-nodes-aws-library"
version = "0.1.0"
description = "AWS CLI nodes for Griptape Nodes Engine"
authors = [
    {name = "Griptape", email = "hello@griptape.ai"}
]
readme = "README.md"
requires-python = "~=3.12"
dependencies = [
    "httpx",
]

[tool.uv.sources]
griptape-nodes-engine = { git = "https://github.com/griptape-ai/griptape-nodes-engine", rev="latest"}

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
